query Dmms {
  dmms {
    title
    image
    movie
    createdAt
  }
}

query Dmm($movie: String!) {
  dmm(where: { movie: $movie }) {
    title
    description
    movie
    createdAt
    image
  }
}

query Posts {
  posts {
    title
    image
    createdAt
    id
  }
}

query Post($id: ID) {
  post(where: { id: $id }) {
    title
    movie
    image
    dmm
    mgs
    createdAt
  }
}
