query Dmms {
  dmms {
    title
    image
    movie
    createdAt
  }
}

query Dmm($movie: String!) {
  dmm(where: { movie: $movie }) {
    title
    description
    movie
    createdAt
    image
  }
}
